# cargo build時の設定
[build]
target = 'x86_64-unknown-uefi'
# target = 'x86_64-uknown-uefi'とすると
# target_os = "uefi"やtarget_arch = "x86_64"などが内部的にrunnerに渡される
rustflags = ["-Cforce-unwind-tables", "-Cforce-frame-pointers", "-Cno-redzone"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]

# cargo runしたときにQEMUを起動する
# cargo runしたとき
# 1. cargo build
# 2. 指定したrunnerをよびだす。bash scripts/launch_qemu.sh <生成されたEFIファイル>
[target.'cfg(target_os = "uefi")']
runner = "bash scripts/launch_qemu.sh"